# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic/grpc/user/User_db.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from logic.grpc.base import base_pb2 as logic_dot_grpc_dot_base_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlogic/grpc/user/User_db.proto\x1a\x1alogic/grpc/base/base.proto\"1\n\x04User\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x15\n\ruser_password\x18\x02 \x01(\t\"+\n\x08JWTToken\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\t\x12\x0f\n\x07refresh\x18\x02 \x01(\t\"\x1f\n\x0cRefreshToken\x12\x0f\n\x07refresh\x18\x01 \x01(\t2\xcc\x01\n\x0bUserTraffic\x12\x1f\n\x0buser_create\x12\x05.User\x1a\t.Response\x12&\n\x0buser_delete\x12\x0c.AccessToken\x1a\t.Response\x12&\n\x0buser_update\x12\x0c.AccessToken\x1a\t.Response\x12\x1e\n\nuser_login\x12\x05.User\x1a\t.JWTToken\x12,\n\rrefresh_token\x12\x0c.AccessToken\x1a\r.RefreshTokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logic.grpc.user.User_db_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=61
  _globals['_USER']._serialized_end=110
  _globals['_JWTTOKEN']._serialized_start=112
  _globals['_JWTTOKEN']._serialized_end=155
  _globals['_REFRESHTOKEN']._serialized_start=157
  _globals['_REFRESHTOKEN']._serialized_end=188
  _globals['_USERTRAFFIC']._serialized_start=191
  _globals['_USERTRAFFIC']._serialized_end=395
# @@protoc_insertion_point(module_scope)
