# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic/_grpc/protos/base.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlogic/_grpc/protos/base.proto\"\x1d\n\x08Response\x12\x11\n\thttp_code\x18\x01 \x01(\t\"\x1d\n\x0b\x41\x63\x63\x65ssToken\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logic._grpc.protos.base_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSE']._serialized_start=33
  _globals['_RESPONSE']._serialized_end=62
  _globals['_ACCESSTOKEN']._serialized_start=64
  _globals['_ACCESSTOKEN']._serialized_end=93
# @@protoc_insertion_point(module_scope)
